//================================================================================
// BOOST SOFTWARE LICENSE
//
// Copyright 2020 BitWise Laboratories Inc.
// Author.......Jim Waschura
// Contact......info@bitwiselabs.com
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.
//================================================================================

#include "pch.h"

#include "BwDevice.h"
#include "UtilTrim.h"

BwDevice::BwDevice() :
	m_IPAddress(NULL),
	m_Port(0),
	m_Connected(false),
	m_FastMode(false),
	m_Socket(NULL)
{
#ifdef _DEBUG
	printf("BwDevice::BwDevice(), Entered\n");
#endif

	m_Socket = new UtilSocket(AF_INET);
}

BwDevice::~BwDevice()
{
#ifdef _DEBUG
	printf("BwDevice::~BwDevice() Entered\n");

#endif
	if (getConnected())
		Disconnect();

	delete m_Socket;
	m_Socket = NULL;
}

void BwDevice::Connect(const char* ipAddress, int port)
{
#ifdef _DEBUG
	printf("BwDevice::Connect(), Entered with ip=%s, port=%d\n",ipAddress,port);
#endif

	if (getConnected())
		throw "[Already_Connected]";

	getSocket()->Connect( ipAddress, port);

	m_Connected = true;
	m_IPAddress = ipAddress;
	m_Port = port;
}

void BwDevice::Disconnect()
{
#ifdef _DEBUG
	printf("BwDevice::bwdev_disconnect(), Entered\n");
#endif
	
	if (getConnected())
	{
		getSocket()->Send("quit\n", 5);
		m_Connected = false;
	}
}

void BwDevice::SendCommand(const char* fmt, ...)
{
#ifdef _DEBUG
	printf("BwDevice::SendCommand(), Entered\n");
#endif

	if (!getConnected())
		throw "[Not_Connected]";

	char Buf[4096];
	va_list argptr;
	va_start(argptr, fmt);
	vsnprintf_s(Buf, 4096, fmt, argptr);
	va_end(argptr);

	if (!getFastMode())
		ClearStatus();

#ifdef _DEBUG
	printf("BwDevice::SendCommand(), send: %s", Buf);
#endif

	getSocket()->Send( Buf, (int)strlen(Buf));

	if (!getFastMode())
	{
		getStatus( Buf, 4096);

		if (strcmp(Buf, "[none]") != 0)
		{
			static char errmsg[1024];
			snprintf(errmsg, 1024, "%s", Buf);
			throw (const char*) errmsg;
		}
	}
}

char * BwDevice::getStatus(char* buffer, int buffersize)
{
#ifdef _DEBUG
	printf("BwDevice::getStatus(), Entered\n");
#endif

	if (buffer == NULL || buffersize <= 0)
		throw "[Bad_Status_Buffer]";

	buffer[0] = 0;

	if (!getConnected())
		throw "[Not_Connected]";

	getSocket()->Send("st?\n", 4);
	int cnt = getSocket()->Receive(buffer, buffersize - 1);
	if (cnt < buffersize)
		buffer[cnt] = 0;

	trim_string(buffer);

#ifdef _DEBUG
	printf("BwDevice::getStatus(), status is: \"%s\"\n", buffer);
#endif

	return buffer;
}

void BwDevice::ClearStatus()
{
#ifdef _DEBUG
	printf("BwDevice::ClearStatus(), Entered\n");
#endif

	if (!getConnected())
		throw "[Not_Connected]";

	getSocket()->Send("stc\n", 4);
}

char *BwDevice::QueryResponse( char* buffer, int buffersize, const char* fmt, ...)
{
#ifdef _DEBUG
	printf("BwDevice::QueryResponse, Entered\n");
#endif
	if (buffer == NULL || buffersize <= 0)
		throw "[Bad_Response_Buffer]";

	if (!getConnected())
		throw "[Not_Connected]";

	buffer[0] = 0;
	char Buf[4096];
	va_list argptr;
	va_start(argptr, fmt);
	vsnprintf_s(Buf, 4096, fmt, argptr);

	va_end(argptr);

	if (!getFastMode())
		ClearStatus();

#ifdef _DEBUG
	printf("BwDevice::SendCommand(), send: %s", Buf);
#endif

	getSocket()->Send(Buf, (int)strlen(Buf));

	int bufcnt = getSocket()->Receive(buffer, buffersize);

	if (bufcnt > 0)
	{
		/* trickle in remaining in case present. */
		getSocket()->SetBlocking(false);
		try
		{
#pragma warning( push )
#pragma warning( disable : 4101 )

			int cnt = 1;
			while (bufcnt < buffersize && cnt > 0 )
			{
				Sleep(100);
				try
				{
					cnt = getSocket()->Receive(buffer + bufcnt, buffersize - bufcnt);
					bufcnt += cnt;
				}
				catch (const char* msg)
				{
					cnt = 0; 
				}
				catch (...)
				{
					throw;
				}
			}

#pragma warning( pop )

			getSocket()->SetBlocking(true);
		}
		catch (...)
		{
			getSocket()->SetBlocking(true);
			throw;
		}
	}

	//int nlcnt = 0;
	//char* ptr = buffer;
	//while ((ptr = strchr(ptr, '\n')) != NULL)
	//{
	//	ptr++; nlcnt++;
	//}

	//if (nlcnt == 1)
	//	trim_string_quotes(buffer);
	//else
		trim_string_end(buffer);

#ifdef _DEBUG
	printf("BwDevice::QueryResponse(), response is: %s\n", buffer);
#endif

	if (!getFastMode())
	{
		getStatus(Buf, 4096);

		if (strcmp(Buf, "[none]") != 0)
		{
			static char errmsg[1024];
			snprintf(errmsg, 1024, "%s", Buf);
			throw (const char*)errmsg;
		}
	}

	return buffer;
}



